
var winName='win0';
var winParent = null;
var modalID = null;
var modalZoomName = null;
var baseKey_win0 = "\x1b";
var altKey_win0 = "0J5678\xbc\xbe\xbf\xde";
var ctrlKey_win0 = "JK";
var saveWarningKeys_win0 = "";
var firstFocusID = null;
var bPTDrag = false;
var refererURL = 'https://campus.concordia.ca/psc/pscsprd/EMPLOYEE/SA/c/SA_LEARNER_SERVICES.SSS_TSRQST_UNOFF.GBL?PORTALPARAM_PTCNAV=HC_SSS_TSRQST_UNOFF_GBL&EOPP.SCNode=SA&EOPP.SCPortal=EMPLOYEE&EOPP.SCName=ADMN_APPSIAN_ACADEMIC&EOPP.SCLabel=&EOPP.SCPTcname=ADMN_SC_SP_APPSIAN_ACADEMIC&FolderPath=PORTAL_ROOT_OBJECT.PORTAL_BASE_DATA.CO_NAVIGATION_COLLECTIONS.ADMN_APPSIAN_ACADEMIC.ADMN_S202006061502363991565943&IsFolder=false&PortalActualURL=https://campus.concordia.ca/psc/pscsprd/EMPLOYEE/SA/c/SA_LEARNER_SERVICES.SSS_TSRQST_UNOFF.GBL&PortalContentURL=https://campus.concordia.ca/psc/pscsprd/EMPLOYEE/SA/c/SA_LEARNER_SERVICES.SSS_TSRQST_UNOFF.GBL&PortalContentProvider=SA&PortalCRefLabel=View%20Unofficial%20Transcript&PortalRegistryName=EMPLOYEE&PortalServletURI=https://campus.concordia.ca/psp/pscsprd/&PortalURI=https://campus.concordia.ca/psc/pscsprd/&PortalHostNode=SA&NoCrumbs=yes&PortalKeyStruct=yes';
var isNewSaveWarn = true;
var bAccessibility_win0 =false;
var bFMode =false;
var bDoModal_win0 = false;
var bJSModal_win0 = false;
var bPromptPage_win0 = false;
var bTabOverTB_win0 = false;
var bTabOverPg_win0 = false;
var bTabOverNonPS_win0 = false;
var PIA_KEYSTRUCT={EMPLID:"40224303"};
var strCurrUrl='https://campus.concordia.ca/psp/pscsprd/EMPLOYEE/SA/c/CU_SELF_SERVICE.CU_STUDENT_RECORD.GBL?EMPLID=40224303';
var strReqURL='https://campus.concordia.ca/psp/pscsprd/EMPLOYEE/SA/c/CU_SELF_SERVICE.CU_STUDENT_RECORD.GBL?EMPLID=40224303&Page=CU_STUDENT_RECORD&Action=U&ForceSearch=Y&EMPLID=40224303';
var bIncInNavigation='T';
var szPinCrefReg='F';
var szCrefID='yyy';
var szCrefReged='F';
var szCrefVisible='F';
var szCrefLabel='zzz';
var localNodes = ['HRMS', 'PSFT_CS', 'PSFT_HR', 'SA'];
var remoteUrls = ['http://my.concordia.ca/psp/upprpr9/EMPLOYEE/CU_REMOTE_UP', 'https://campus.concordia.ca/psp/pscsprd/EMPLOYEE/PSFT_PA'];
bGenDomInfo = false;
var szCalendarType = 'G';
var bMenuSrchPage = false;
var bGuidedAG = false;
var bWSRP=0;var szMenuSrchText = "-999999-";
var disablePNSubscriptions=0;var modalCloseUrl = '/cs/pscsprd/cache_1/PT_TRANS_16PIX_1.png';
var modalCloseAlt = 'Close';
var modalResizeUrl= '/cs/pscsprd/cache_1/PT_RESIZE_IMG_1.svg';
var modalResizeAlt = 'Drag to resize';
var modalMoveAlt = 'Drag to move';
